import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

import { toPascal, toSnake } from "ts-case-convert";

// eslint-disable-next-line
// @ts-ignore
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const LIBRARY_PATH = "libs/fridgeezy/types/src/lib";
const INPUT_PATH = `${LIBRARY_PATH}/database.types.ts`;
const OUTPUT_PATH = `${LIBRARY_PATH}/entities`;

function findProjectRoot(startDir: string): string {
    let currentDir = startDir;

    while (currentDir !== dirname(currentDir)) {
        // Look for monorepo markers (nx.json, pnpm-workspace.yaml, lerna.json)
        // or a package.json with workspaces field
        const hasNxJson = existsSync(join(currentDir, "nx.json"));
        const hasPnpmWorkspace = existsSync(
            join(currentDir, "pnpm-workspace.yaml")
        );
        const hasLerna = existsSync(join(currentDir, "lerna.json"));

        const packageJsonPath = join(currentDir, "package.json");
        if (existsSync(packageJsonPath)) {
            const packageJson = JSON.parse(
                readFileSync(packageJsonPath, "utf-8")
            );
            if (
                hasNxJson ||
                hasPnpmWorkspace ||
                hasLerna ||
                packageJson.workspaces
            ) {
                return currentDir;
            }
        }

        currentDir = dirname(currentDir);
    }

    throw new Error("Could not find project root (no monorepo markers found)");
}

const projectRoot = findProjectRoot(__dirname);
const databaseTypesPath = join(projectRoot, INPUT_PATH);
const outputDir = join(projectRoot, OUTPUT_PATH);

function extractTableNames(content: string) {
    const tablesMatch = content.match(/Tables:\s*\{([\s\S]*?)\n\s{4}\}/);
    if (!tablesMatch) {
        throw new Error(
            "Could not find Tables definition in database.types.ts"
        );
    }

    const tablesContent = tablesMatch[1];
    const tableNames = new Set();

    const lines = tablesContent.split("\n");

    for (const line of lines) {
        const match = line.match(/^\s{6}(\w+):\s*\{/);
        if (match) {
            const tableName = match[1];
            if (
                !["Row", "Insert", "Update", "Relationships"].includes(
                    tableName
                )
            ) {
                tableNames.add(tableName);
            }
        }
    }

    return Array.from(tableNames) as string[];
}

function generateEntityTypeFile(tableName: string) {
    const entityName = toPascal(tableName);

    return `import { Tables, TablesInsert, TablesUpdate } from "../database.types";

export type ${entityName} = Tables<"${tableName}">;

export type ${entityName}InsertPayload = TablesInsert<"${tableName}">;

export type ${entityName}UpdatePayload = TablesUpdate<"${tableName}">;
`;
}

function generateIndexFile(tableNames: string[]) {
    const header = `// Auto-generated entity types - DO NOT EDIT MANUALLY
// Generated by: npm run generate:types
// To regenerate: Run the generate:types script after updating database.types.ts

`;
    const exports = tableNames
        .map((name) => `export * from './${name}';`)
        .join("\n");

    return header + exports + "\n";
}

function main() {
    console.log("Reading database types...");

    const databaseTypesContent = readFileSync(databaseTypesPath, "utf-8");

    console.log("Extracting table names...");

    const tableNames = extractTableNames(databaseTypesContent);

    console.log(`Found ${tableNames.length} tables:`);

    tableNames.forEach((name) => console.log(`  - ${name}`));

    console.log("\nGenerating entity type files...");

    tableNames.forEach((tableName) => {
        const fileName = `${toSnake(tableName)}.ts`;
        const filePath = join(outputDir, fileName);
        const content = generateEntityTypeFile(tableName);

        writeFileSync(filePath, content, "utf-8");

        console.log(`  ✓ Generated ${fileName}`);
    });

    console.log("\nGenerating index file...");

    const indexFilePath = join(outputDir, "index.ts");
    const indexContent = generateIndexFile(tableNames);

    writeFileSync(indexFilePath, indexContent, "utf-8");

    console.log("  ✓ Generated entities.ts");

    console.log("\nGeneration complete!");
    console.log("\nNext steps:");
    console.log(`1. Review the generated files in ${OUTPUT_PATH}`);
    console.log(
        '2. Import entity types from "@fridgeezy/supabase" or use the entities.ts barrel export'
    );
}

main();
