import { injectable, inject } from "tsyringe";
import type OpenAI from "openai";
import {
    ISuggestionGeneratorService,
    GenerateSuggestionRequest,
    GeneratedSuggestionDto,
} from "@fridgeezy/domain";
import { castArray } from "@fridgeezy/toolkit";
import { processJsonlStream } from "@fridgeezy/streaming-server";
import { GenerateSuggestionResponseSchema } from "@fridgeezy/schemas";

/**
 * Service for generating recipe suggestions using OpenAI.
 *
 * Encapsulates:
 * - Prompt construction (domain knowledge)
 * - AI service interaction (infrastructure)
 * - Response streaming and validation
 */
@injectable()
export class SuggestionGeneratorService
    implements ISuggestionGeneratorService
{
    constructor(
        @inject("OpenAIClient") private readonly openai: OpenAI
    ) {}

    /**
     * Generate recipe suggestions based on criteria.
     *
     * Yields suggestions as they are generated by the AI model.
     */
    async *generateSuggestions(
        request: GenerateSuggestionRequest
    ): AsyncIterable<GeneratedSuggestionDto> {
        const systemPrompt = this.buildSystemPrompt();
        const userPrompt = this.buildUserPrompt(request);

        const stream = await this.openai.chat.completions.create({
            model: "gpt-4.1",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: userPrompt },
            ],
            stream: true,
        });

        // Process JSONL stream with validation
        for await (const { parsed } of processJsonlStream(stream, [
            GenerateSuggestionResponseSchema,
        ])) {
            yield parsed as GeneratedSuggestionDto;
        }
    }

    /**
     * Build system prompt with generation rules and constraints.
     * Encapsulates domain knowledge about recipe generation.
     */
    private buildSystemPrompt(): string {
        return `You are a recipe suggestion assistant. Generate exactly 5 authentic, real-world recipe suggestions based on the provided ingredients.

## Rules
- Suggest 5 authentic, well-known recipes that use the provided ingredients.
- Each recipe MUST be a real dish (not invented, must be authentic) with their real name.
- If a combination is not authentic (e.g., rosemary in Thai cuisine), do NOT invent dishes. Generate an empty array instead! VERY IMPORTANT!
- Do NOT include recipes where a blacklisted item is normally present.
- The name must be the authentic name (e.g., Murgh Makhani, NOT Indian Tomato Butter Chicken). Do NOT add alternative names in parenthesis.

## Difficulty Levels
- "easy": Beginner-friendly version of the dish, using simple techniques while keeping ingredients authentic.
- "medium": The standard authentic recipe with its usual techniques.
- "hard": Elevated or advanced version of the dish, which may include optional ingredients or more complex techniques.

## Tagging Rules (CRITICAL)
- EXACTLY 1 component tag per recipe:
  - Use the specific component type if it matches (e.g., roux for a roux, sauce for bechamel, stock for a stock)
  - Use "dish" for regular finished dishes/meals
- EXACTLY 1 cuisine tag per recipe (the most accurate cuisine origin)
- Include ALL applicable dietary tags (e.g., vegan, gluten_free, dairy_free if the recipe qualifies)

## Output Format
Output EXACTLY 5 recipes, one JSON object per line (JSONL format). No markdown, no code blocks, no extra text.

Each recipe object must include:
- name
- description (max 50 characters)
- difficulty (easy, medium, or hard)
- ingredients (array of strings)
- tags (array of strings with component, cuisine, and dietary tags)`;
    }

    /**
     * Build user prompt with specific generation criteria.
     */
    private buildUserPrompt(request: GenerateSuggestionRequest): string {
        const formatFilter = (filter: string, value?: string | string[]) => {
            const isValid = Array.isArray(value) ? value.length > 0 : !!value;
            return isValid ? `${filter}: ${castArray(value).join(",")}` : "";
        };

        return [
            formatFilter("Blacklist", request.blacklist),
            formatFilter("Component", request.component),
            formatFilter("Course", request.course),
            formatFilter("Cuisine", request.cuisine),
            formatFilter("Difficulty", request.difficulty),
            formatFilter("Dietary Restrictions", request.dietaryRestrictions),
            formatFilter("Ingredients", request.ingredients),
        ]
            .filter(Boolean)
            .join("\n");
    }
}
