export const CUISINES = [
  "All",
  "American",
  "Asian",
  "Barbecue",
  "British",
  "Brazilian",
  "Chinese",
  "Cajun & Creole",
  "Central europe",
  "Cuban",
  "Caribbean",
  "English",
  "Eastern europe",
  "French",
  "Filipino",
  "Greek",
  "German",
  "Hawaiian",
  "Hungarian",
  "Irish",
  "Indian",
  "Italian",
  "South east asian",
  "Jamaican",
  "Korean",
  "Mexican",
  "Mediterranean",
  "Middle eastern",
  "Moroccan",
  "Nordic",
  "Portuguese",
  "Southwestern",
  "Southern & Soul Food",
  "South american",
  "South east asian",
  "Spanish",
  "Swedish",
  "Thai",
  "Turkish",
  "Vietnamese",
] as const;

export const DIETARY_TAGS = [
  "VEGETARIAN",
  "VEGAN",
  "PLANT_BASED",
  "DAIRY_FREE",
  "GLUTEN_FREE",
] as const;

export const MEAL_TIMES = [
  "ALL",
  "BREAKFAST",
  "LUNCH",
  "DINNER",
  "SNACK",
  "TREAT_DESSERT",
] as const;

export const COURSE_TYPES = [
  "APPETIZER",
  "MAIN_COURSE",
  "SIDE_DISH",
  "DESSERT",
  "SALAD",
  "SOUP",
  "BEVERAGE",
] as const;

export const DISH_COMPONENTS = [
  "COMPLETE_DISH",
  "SAUCE",
  "MARINADE",
  "DRESSING",
  "SEASONING",
  "BASE",
  "TOPPING",
] as const;

export const COMMON_ALLERGENS = [
  "DAIRY",
  "EGGS",
  "FISH",
  "SHELLFISH",
  "TREE_NUTS",
  "PEANUTS",
  "WHEAT",
  "SOY",
  "SESAME",
  "GLUTEN",
  "LACTOSE",
  "SULFITES",
] as const;
