-- Seed categories with 20 user-friendly categories
-- canonical_id is auto-generated by trigger (e.g., "Fats & Oils" -> "fats_oils")
insert into categories (name, description)
values ('Meats', 'Red meats, poultry, and game'),
       ('Seafood', 'Fish, shellfish, crustaceans'),
       ('Eggs', 'Chicken, duck, quail eggs'),
       ('Dairy', 'Milk, cream, yogurt, butter, cheese'),
       ('Vegetables', 'All vegetables including roots, greens'),
       ('Fruits', 'Fresh and dried fruits, berries'),
       ('Grains', 'Rice, quinoa, oats, wheat, barley, couscous'),
       ('Legumes', 'Beans, lentils, peas, chickpeas'),
       ('Nuts & Seeds', 'Tree nuts, peanuts, and seeds'),
       ('Herbs & Spices', 'Fresh/dried herbs, spices, seasonings'),
       ('Mushrooms', 'All fungi varieties'),
       ('Noodles', 'All pasta and Asian noodles'),
       ('Breads', 'Bread, tortillas, pita, wraps, crackers'),
       ('Fats & Oils', 'Cooking oils and solid fats'),
       ('Sweeteners', 'Sugar, honey, maple syrup, agave'),
       ('Stocks', 'Broths, stocks, bouillon'),
       ('Sauces', 'Sauces, condiments, dressings'),
       ('Vinegars', 'All vinegar types'),
       ('Beverages', 'Alcoholic and non-alcoholic drinks'),
       ('Baking', 'Baking powder, soda, yeast, flour, extracts');
