-- Seed categories with comprehensive set covering 99% of ingredients
insert into categories (name, description)
values ('meat', 'Red meats: beef, pork, lamb, veal, game'),
       ('poultry', 'Chicken, turkey, duck, quail, etc.'),
       ('seafood', 'Fish, shellfish, crustaceans, mollusks'),
       ('egg', 'Chicken eggs, duck eggs, quail eggs'),
       ('dairy', 'Milk, cream, yogurt, butter, ice cream'),
       ('cheese', 'All cheese varieties'),
       ('vegetable', 'All vegetables including roots, greens, squashes'),
       ('fruit', 'Fresh and dried fruits, berries'),
       ('mushroom', 'All fungi varieties'),
       ('grain', 'Whole grains: wheat, oats, barley, quinoa, etc.'),
       ('rice', 'All rice varieties: white, brown, wild, jasmine, basmati'),
       ('pasta', 'Dried and fresh pasta, noodles (non-Asian)'),
       ('noodle', 'Asian noodles: ramen, udon, soba, rice noodles'),
       ('bread', 'Bread, rolls, tortillas, pita, buns'),
       ('flour', 'All-purpose, bread, cake, whole wheat, specialty flours'),
       ('legume', 'Beans, lentils, peas, chickpeas'),
       ('nut', 'Tree nuts and peanuts'),
       ('seed', 'Seeds used in cooking: sesame, sunflower, pumpkin'),
       ('herb', 'Fresh and dried herbs: basil, parsley, cilantro, rosemary'),
       ('spice', 'Ground and whole spices: cumin, paprika, cinnamon'),
       ('seasoning', 'Salt, pepper, MSG, seasoning blends'),
       ('oil', 'Cooking oils: olive, vegetable, sesame, coconut'),
       ('fat', 'Solid fats: lard, shortening, ghee, tallow'),
       ('condiment', 'Ketchup, mustard, mayo, hot sauce, soy sauce'),
       ('sauce', 'Prepared sauces: tomato sauce, pesto, curry paste'),
       ('stock', 'Broths, stocks, bouillon'),
       ('vinegar', 'All vinegar types: balsamic, rice, wine, apple cider'),
       ('sweetener', 'Sugar, honey, maple syrup, agave, artificial sweeteners'),
       ('baking', 'Baking powder, baking soda, yeast, cream of tartar'),
       ('extract', 'Vanilla extract, almond extract, flavorings'),
       ('alcohol', 'Wine, beer, spirits used in cooking'),
       ('beverage', 'Non-alcoholic drinks: juice, tea, coffee, soda'),
       ('preserves', 'Jams, jellies, pickles, chutneys'),
       ('canned', 'Canned goods that don''t fit other categories'),
       ('other', 'Miscellaneous ingredients');
