import { GenerateRecipeResponseDto } from "@fridgeezy/schemas";
import { supabaseAdmin } from "@fridgeezy/supabase";

export async function fetchRecipe(
    recipeId: string
): Promise<GenerateRecipeResponseDto | null> {
    const { data: recipe, error } = await supabaseAdmin
        .from("recipes")
        .select(
            `
            name,
            description,
            difficulty,
            servings,
            prep_time,
            cook_time,
            tips,
            recipe_ingredients (
                quantity,
                ingredient:ingredients (
                    name,
                    category:categories (name),
                    parent_ingredient:ingredients!parent_id (name)
                ),
                unit:units (abbreviation)
            ),
            recipe_instructions (
                step_number,
                instruction_text
            ),
            recipe_tags (
                tag:tags (name)
            )
        `
        )
        .eq("id", recipeId)
        .single();

    if (error || !recipe) {
        return null;
    }

    // Transform database format to RecipeResponse format
    return {
        name: recipe.name,
        description: recipe.description || "",
        difficulty: recipe.difficulty!,
        servings: recipe.servings,
        prepTime: parseInt(recipe.prep_time?.replace(" min", "") || "0"),
        cookTime: parseInt(recipe.cook_time?.replace(" min", "") || "0"),
        ingredients: recipe.recipe_ingredients.map((ri) => ({
            name: ri.ingredient.name,
            category: ri.ingredient.category?.name ?? "",
            parent: ri.ingredient.parent_ingredient?.name || null,
            quantity: ri.quantity,
            unit: ri.unit.abbreviation,
        })),
        instructions: recipe.recipe_instructions
            .sort((a, b) => a.step_number - b.step_number)
            .map((inst) => ({
                text: inst.instruction_text,

                ingredients: [], // Will be regenerated by AI
            })),
        tips:
            recipe.tips && recipe.tips.length > 0
                ? recipe.tips.map((text) => ({ text }))
                : null,
        tags: recipe.recipe_tags.map((rt) => rt.tag.name),
    };
}
