import { GenerateRecipeResponseDto } from "@fridgeezy/schemas";
import { supabaseAdmin } from "@fridgeezy/supabase";

export async function fetchRecipe(
    recipeId: string
): Promise<
    | (GenerateRecipeResponseDto & {
          imageUrl?: string;
          origin?: string | null;
          /**
           * Owning profile, or null for the shared catalogue. Read through the
           * service-role client, which sees past RLS — so a caller handing this
           * recipe to somebody must check it with `callerMayReadRecipe` first.
           */
          createdBy?: string | null;
      })
    | null
> {
    const { data: recipe, error } = await supabaseAdmin
        .from("recipes")
        .select(
            `
            id,
            name,
            name_en,
            description,
            difficulty,
            servings,
            prep_time,
            cook_time,
            kcal,
            carbs,
            protein,
            fat,
            tips,
            image,
            origin,
            created_by,
            recipe_ingredients (
                quantity,
                ingredient:ingredients (
                    name,
                    category:categories (name),
                    parent_ingredient:ingredients!parent_id (name)
                ),
                unit:units (abbreviation)
            ),
            recipe_instructions (
                step_number,
                instruction_text,
                title,
                duration_seconds,
                temperature_c,
                equipment
            ),
            recipe_tags (
                tag:tags (name)
            )
        `
        )
        .eq("id", recipeId)
        .single();

    if (error || !recipe) {
        return null;
    }

    // Transform database format to RecipeResponse format
    return {
        id: recipe.id,
        name: recipe.name,
        nameEn: recipe.name_en ?? null,
        description: recipe.description || "",
        difficulty: recipe.difficulty as "easy" | "medium" | "hard",
        servings: recipe.servings,
        prepTime: parseInt(recipe.prep_time?.replace(" min", "") || "0"),
        cookTime: parseInt(recipe.cook_time?.replace(" min", "") || "0"),
        kcal: recipe.kcal || 0,
        carbs: recipe.carbs || 0,
        protein: recipe.protein || 0,
        fat: recipe.fat || 0,
        ingredients: recipe.recipe_ingredients.map((ri) => ({
            name: ri.ingredient.name,
            category: ri.ingredient.category?.name ?? "",
            parent: ri.ingredient.parent_ingredient?.name || null,
            quantity: ri.quantity,
            unit: ri.unit.abbreviation,
        })),
        instructions: recipe.recipe_instructions
            .sort((a, b) => a.step_number - b.step_number)
            .map((inst) => ({
                text: inst.instruction_text,
                title: inst.title ?? undefined,
                // Carried through so modify/escalate can show the source
                // recipe's timings; both regenerate their own, but a step the
                // model leaves untouched keeps the duration it already had.
                durationSeconds: inst.duration_seconds ?? undefined,
                temperatureC: inst.temperature_c ?? undefined,
                equipment: inst.equipment ?? undefined,
                ingredients: [], // Will be regenerated by AI
            })),
        tips:
            recipe.tips && recipe.tips.length > 0
                ? recipe.tips.map((text) => ({ text }))
                : null,
        tags: recipe.recipe_tags.map((rt) => rt.tag.name),
        imageUrl: recipe.image, // Include image URL for reuse
        // Provenance, carried so modify/escalate can keep it off an adapted
        // copy's read path by accident — see 20260815000003.
        origin: recipe.origin ?? null,
        createdBy: recipe.created_by ?? null,
    } as GenerateRecipeResponseDto & {
        imageUrl?: string;
        origin?: string | null;
        createdBy?: string | null;
    };
}
