import { PROSE_CSS, renderPage, SITE_NAME, SUPPORT_EMAIL } from "./chrome";

/**
 * The support page — the URL App Store Connect asks for.
 *
 * One contact channel and the questions people actually hit. The FAQ uses
 * native `<details>` so the page stays script-free; the answers state the
 * honest current paths (account deletion is by email until the app grows an
 * in-app flow).
 */

const BODY = `
<main class="prose">
  <h1>Support</h1>
  <p class="lede">Stuck, curious, or found something odd? We read everything.</p>

  <div class="card">
    <p><strong>Email us:</strong> <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></p>
    <p style="margin-bottom:0">It helps to include your iPhone model, iOS version, and the
    email you signed in with — screenshots welcome.</p>
  </div>

  <h2>Common questions</h2>

  <details>
    <summary>How do I restore my subscription?</summary>
    <p>In the app, open Settings → Subscription and choose restore. Purchases
    follow your Apple&nbsp;ID, so a new phone or a reinstall picks them up —
    make sure you're signed in with the same Apple&nbsp;ID you bought with.</p>
  </details>

  <details>
    <summary>How do I cancel my subscription?</summary>
    <p>Subscriptions are managed by the App Store: open Settings on your iPhone
    → your name → Subscriptions → ${SITE_NAME}. Cancelling stops the renewal;
    you keep access until the end of the period you've paid for.</p>
  </details>

  <details>
    <summary>How do I delete my account and data?</summary>
    <p>Email us at <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a> from
    the address you signed in with and we'll delete your account and everything
    stored with it. Ingredients, recipes and lists can also be removed directly
    in the app at any time.</p>
  </details>

  <details>
    <summary>A recipe looks wrong or unsafe</summary>
    <p>Recipes are generated by AI and can make mistakes. If something looks
    off — an ingredient that doesn't belong, a temperature that seems wrong —
    trust your judgement, skip it, and tell us. Always check for your own
    allergies and cook meat, fish and eggs to safe temperatures.</p>
  </details>

  <details>
    <summary>My fridge photo isn't recognized</summary>
    <p>Good light and a straight-on shot help most, and a couple of closer
    photos beat one wide one. Photos are only used to recognize ingredients —
    they aren't kept after processing.</p>
  </details>

  <h2>Privacy &amp; legal</h2>
  <p>The details live in the <a href="/privacy">Privacy Policy</a> and the
  <a href="/terms">Terms of Use</a>.</p>
</main>
`;

export function renderSupportPage(origin?: string): string {
    return renderPage({
        title: `Support — ${SITE_NAME}`,
        description: `Help with ${SITE_NAME}: subscriptions, account deletion, and getting in touch.`,
        origin,
        path: "/support",
        styles: PROSE_CSS,
        body: BODY,
    });
}
