import { PROSE_CSS, renderPage, SITE_NAME, SUPPORT_EMAIL } from "./chrome";

/**
 * Terms of use.
 *
 * The app currently points its Terms button at Apple's standard Licensed
 * Application EULA; these terms keep that as the licence baseline and add the
 * product-specific parts Apple's text cannot cover — above all the AI food
 * safety disclaimer, which is the clause this product genuinely needs.
 *
 * DRAFT until reviewed by a human, like the privacy policy: governing law and
 * provider identification want a once-over before this goes live on a domain.
 */

const APPLE_EULA =
    "https://www.apple.com/legal/internet-services/itunes/dev/stdeula/";

const BODY = `
<main class="prose">
  <h1>Terms of Use</h1>
  <p class="updated">Last updated: 9 August 2026</p>

  <p class="lede">The short version: cook with your head as well as the app,
  subscriptions renew until you cancel them, and be kind to the service.</p>

  <h2>1. The agreement</h2>
  <p>These terms apply to the ${SITE_NAME} app and this website. The app is
  licensed to you under
  <a href="${APPLE_EULA}">Apple's Licensed Application End User License
  Agreement</a>; where these terms cover something specific to ${SITE_NAME},
  these terms apply on top of it.</p>

  <h2>2. What ${SITE_NAME} is</h2>
  <p>${SITE_NAME} recognizes the ingredients you have and uses AI to suggest
  and generate recipes, cooking guidance, substitutes and menus from them.</p>

  <h2>3. Cooking safety — please read this one</h2>
  <p>Recipes and suggestions are <strong>generated by AI</strong> and can be
  wrong. They are inspiration and guidance, not professional, dietary or
  medical advice. You are responsible for what you cook and eat:</p>
  <ul>
    <li><strong>Allergies and intolerances.</strong> Always check every
    ingredient yourself, even when you've set dietary preferences — the app
    can miss things.</li>
    <li><strong>Food safety.</strong> Cook meat, fish, and eggs to safe
    temperatures, and use your judgement about freshness and hygiene.
    Temperatures and timings in recipes are estimates.</li>
    <li>If a recipe looks wrong, don't cook it — and we'd love to hear about
    it at <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</li>
  </ul>

  <h2>4. Your account</h2>
  <p>Keep your sign-in method to yourself and give us accurate information. We
  can suspend or close accounts that abuse the service or these terms.</p>

  <h2>5. Subscriptions</h2>
  <p>Some features require an auto-renewable subscription. Payment is charged
  to your Apple&nbsp;ID at confirmation of purchase; the subscription renews
  automatically unless cancelled at least 24 hours before the end of the
  current period, and you can manage or cancel it in your App Store account
  settings. Refunds are handled by Apple under their policies.</p>

  <h2>6. Fair use</h2>
  <p>Don't misuse the service: no unlawful use, no attempts to break, overload
  or reverse-engineer it, no scraping it, and no using it to build a competing
  ingredient-to-recipe service. Recipe generation costs real money per request,
  so automated or excessive use may be limited.</p>

  <h2>7. Content</h2>
  <p>The app, its artwork and its generated content belong to us or our
  licensors. Your own data — your ingredients, notes and lists — stays yours.
  You can cook, share and adapt any recipe the app gives you; that's what it's
  for.</p>

  <h2>8. Liability</h2>
  <p>The service is provided as-is. To the extent permitted by law, we are not
  liable for indirect damages or for outcomes of cooking decisions made against
  section 3. Nothing in these terms limits liability that cannot be limited by
  law, or your statutory rights as a consumer.</p>

  <h2>9. Changes and ending</h2>
  <p>We may update these terms as the product evolves; the date above tells you
  when. If a change matters, we'll say so in the app. You can stop using
  ${SITE_NAME} at any time, and <a href="/support">have your account
  deleted</a>.</p>

  <h2>10. Contact</h2>
  <p><a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></p>
</main>
`;

export function renderTermsPage(origin?: string): string {
    return renderPage({
        title: `Terms of Use — ${SITE_NAME}`,
        description: `The terms for using ${SITE_NAME}, including the AI cooking safety disclaimer.`,
        origin,
        path: "/terms",
        styles: PROSE_CSS,
        body: BODY,
    });
}
