------------------------------------------------------------------------------
-- profile_chat_conversations: the transcript, not the log
------------------------------------------------------------------------------
--
-- Chat history has lived on ONE PHONE since it was built. The client's
-- `CHAT_HISTORY_STORE` (zustand + AsyncStorage) is the whole of it, and
-- `clearOnSessionEnd` empties it on sign-out — correctly, because the history
-- sheet opens from the chat tab with no account check anywhere between, so a
-- shared phone would otherwise hand the next person the last one's questions
-- and let them carry on the thread. The clear is right and stays. What was
-- missing was the way back IN: signing into your own account restored nothing,
-- and a second device had never heard of you.
--
-- ## This is NOT profile_prompts, and the difference decides the RLS
--
-- `20260822000004` records every prompt on its way to a model and is
-- deliberately **writable by nobody** — "a forgeable record is worse than no
-- record". That argument is exactly right for what that table is: evidence of
-- what a person asked, read as a log.
--
-- This table is a different object. It is the cook's own DOCUMENT — the thread
-- as they last saw it — and it is read by exactly one person, its author. There
-- is nothing to forge: writing a conversation you never had into your own
-- history harms nobody and proves nothing to anyone. So it takes the
-- `pantry_items` / `shopping_lists` shape instead: owner-scoped on all four
-- verbs, written by the client.
--
-- The two are complements and both are kept. `profile_prompts` stays the
-- unforgeable record of what was sent to a model; this is what the reader gets
-- back. Neither can be derived from the other — which is the second, harder
-- reason this one cannot be server-written:
--
-- ## The server cannot assemble a transcript, so the client stores it
--
-- What a chat turn PRODUCES is not text. It is a reply plus, variously,
-- suggestion cards, a menu card, a change proposal and what a photograph was
-- read to contain — and all of that is assembled on the device, by the frame
-- reducer, out of an SSE stream the API emits and never accumulates. Writing
-- this server-side would mean buffering every stream and re-implementing that
-- reducer behind it, to arrive at a worse copy of something the client is
-- holding already. So the client sends the rendered thread, whole.
--
-- ## One row per conversation, replaced on every turn
--
-- Not an append-only log of turns. The client already owns the thread as an
-- array and rewrites it in place; a per-turn log would have to be re-ordered
-- and re-assembled on read, and would still not say which turns had since been
-- edited (a proposal accepted or declined mutates a message that has already
-- landed). `id` is the client's own `conversationId` — the same uuid
-- `profile_prompts.conversation_id` groups by, so the two tables join without
-- anything being threaded through to make them.
--
-- ## Bounded by construction
--
-- A trigger prunes to the newest 60 conversations per profile on every insert,
-- the same rule `record_prompt` applies to its 200 and for the same reason:
-- there is no scheduler here, and a retention rule nothing runs is not a
-- retention rule. A trigger rather than an RPC because the writer is the
-- client — there is no server hop to hang the prune off.
--
-- 60 rather than 200 because a row here is a whole thread with its cards, not
-- one sentence. Set by hand, like `record_prompt`'s cap, and chosen so a heavy
-- user's table stays in the low megabytes rather than the tens of kilobytes.

create table if not exists profile_chat_conversations
(
    -- The client's `conversationId` — generated by `createConversationId` and
    -- already the key every turn of this thread was recorded under in
    -- `profile_prompts`. Client-supplied rather than defaulted, so a second
    -- device syncing the same thread updates it instead of forking it.
    id         uuid primary key,
    profile_id uuid                     not null references profiles (id) on delete cascade,
    -- What the drawer's row says. Derived on the client by `deriveTitle`, which
    -- names the thread for the DISH it found rather than for the question that
    -- started it — so it is a rendering decision, and it is stored rather than
    -- recomputed because the server cannot make it.
    title      text                     not null,
    -- The rendered thread: `Message[]` as the client draws it, cards and all.
    -- Opaque here on purpose. Nothing in the database reads inside it, no
    -- constraint asserts its shape, and no view unpacks it — the one reader is
    -- the client that wrote it, and pinning the shape in SQL would put a
    -- migration in front of every change to a chat bubble.
    messages   jsonb                    not null,
    -- Last write wins across devices, and the client sends its own clock rather
    -- than taking `now()`: the value has to be comparable with the copy already
    -- in AsyncStorage on a phone that may have been offline, and only the device
    -- knows when that one was written.
    updated_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now(),

    -- A thread with nothing in it is what an abandoned tap produces, and it
    -- would occupy a row and a drawer line saying nothing. The client does not
    -- save one; this is what stops a future one doing it by accident.
    constraint profile_chat_conversations_messages_check
        check (jsonb_typeof(messages) = 'array' and jsonb_array_length(messages) > 0),
    constraint profile_chat_conversations_title_check
        check (char_length(btrim(title)) between 1 and 200)
);

-- The drawer: this profile's threads, newest first. `id` breaks the tie so the
-- order is stable when two land in the same millisecond, which a device
-- flushing a backlog on reconnect does.
create index if not exists idx_profile_chat_conversations_profile_updated
    on profile_chat_conversations using btree (profile_id, updated_at desc, id desc);

comment on table profile_chat_conversations is
    'Chat threads as the client renders them, newest 60 per profile. Owner-written, unlike profile_prompts next door: this is the reader''s own document rather than a record of what was asked, and only the client can assemble it.';

comment on column profile_chat_conversations.messages is
    'The rendered Message[] — replies, suggestion cards, menus, proposals. Opaque to the database by design; the only reader is the client that wrote it.';

comment on column profile_chat_conversations.updated_at is
    'Client clock, not now(): it is compared against a copy in the device''s own storage, which may have been written offline.';

------------------------------------------------------------------------------
-- RLS: the owner's own document, on all four verbs
------------------------------------------------------------------------------
--
-- `pantry_items`' shape rather than `profile_prompts`'. See the header: there
-- is nothing here worth forging, and the writer has to be the client because
-- the server never assembles a thread.

alter table profile_chat_conversations enable row level security;

drop policy if exists users_read_own_chats on profile_chat_conversations;
create policy users_read_own_chats on profile_chat_conversations for select
    using (profile_id = current_profile_id());

drop policy if exists users_write_own_chats on profile_chat_conversations;
create policy users_write_own_chats on profile_chat_conversations for insert
    with check (profile_id = current_profile_id());

drop policy if exists users_update_own_chats on profile_chat_conversations;
create policy users_update_own_chats on profile_chat_conversations for update
    using (profile_id = current_profile_id())
    with check (profile_id = current_profile_id());

drop policy if exists users_forget_own_chats on profile_chat_conversations;
create policy users_forget_own_chats on profile_chat_conversations for delete
    using (profile_id = current_profile_id());

------------------------------------------------------------------------------
-- The cap
------------------------------------------------------------------------------
--
-- On INSERT only. An update is a thread growing by a turn and cannot take the
-- profile over the limit, so running the prune there would be a bounded index
-- walk on every single message committed, for a count that has not changed.

create or replace function public.prune_profile_chat_conversations()
    returns trigger
    language plpgsql
as
$function$
declare
    -- How many threads a profile keeps. A product statement about how far back
    -- a history drawer is worth scrolling, not a number fitted to anything —
    -- the same exception `record_prompt`'s 200 occupies.
    v_limit constant integer := 60;
begin
    delete
    from profile_chat_conversations c
    where c.profile_id = new.profile_id
      and c.id not in (select keep.id
                       from profile_chat_conversations keep
                       where keep.profile_id = new.profile_id
                       order by keep.updated_at desc, keep.id desc
                       limit v_limit);

    return null;
end;
$function$;

comment on function public.prune_profile_chat_conversations() is
    'Keeps the newest 60 threads per profile. AFTER INSERT only: an update cannot raise the count.';

drop trigger if exists prune_chat_conversations on profile_chat_conversations;
create trigger prune_chat_conversations
    after insert
    on profile_chat_conversations
    for each row
execute function public.prune_profile_chat_conversations();

notify pgrst, 'reload schema';
