// Load environment variables first (auto-loads when imported)
import "dotenv/config";

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { buildFoodIllustrationStyle, generateImage } from "@fridgeezy/genai";

/**
 * Candidates for the crash screen: an ingredient with a drawn face.
 *
 * ## Why this is its own operation and not a scene in `generate-client-art`
 *
 * Every other illustration in the app goes through `buildFoodIllustrationStyle`
 * unedited, and its trailer ends "Not photorealistic, not 3D-rendered, **not
 * cartoonish**, not high-contrast." A face is outside that, so this is the one
 * surface whose prompt has to reach into the shared style and take a clause
 * out.
 *
 * Doing it HERE rather than adding a `character` option to the builder is
 * deliberate, and it is the same containment `generate-app-icon` and
 * `generate-splash` already use: an option on the builder is a door, and the
 * next surface that fancies a mascot would find it open. An operation is a
 * one-off by construction. The cost is that these are generated by hand and
 * committed, so nothing regenerates them by accident — which is the right trade
 * for the only picture in the app with eyes in it.
 *
 * ## The clause is REMOVED, not replaced with a copy of the style
 *
 * `allowDrawnFace` edits the built string and throws if the clause it expects
 * is not there. Pasting an edited copy of the eight FIXED STYLE lines would
 * work today and silently drift the moment anybody touches the shared block —
 * which is the exact failure `buildFoodIllustrationStyle`'s own header records
 * from when the two call sites each kept their own paragraph. This way a change
 * to the trailer fails loudly here instead.
 *
 * What holds the line in the clause's place is `FACE_RULE`, which is much
 * narrower than "not cartoonish": a face made only of the linework already in
 * the picture, no features beyond five marks, and explicitly not a creature.
 *
 * ## What is being compared
 *
 * One variable. The face rule, the framing, the camera and the mood are
 * identical across all five; only the ingredient and its own way of sagging
 * change. Each subject has to fail in its SHAPE — droop, split, slump, wilt —
 * because that is what survives the pale chalky register. None of them is
 * mouldy or spotted: this is a food app, and food that has gone OFF is a
 * different and much worse sentence than food that is having a bad day.
 *
 * Composed for a disc, like every medallion — subject centred, about two thirds
 * of the frame, corners expendable. Three-quarter rather than the overhead the
 * other medallions use, because a face seen from directly above is not a face.
 */

/** Said to every scene — see `generate-client-art`, where it is not boilerplate. */
const SINGLE_IMAGE_RULE = `- This is ONE single illustration of ONE subject, filling the whole frame as a single continuous picture. Never a grid, contact sheet, collage, diptych, triptych, quadtych, mood board, set of variations, or a frame divided into panels or quadrants by any line, gutter or border.`;

/**
 * The narrow permission that replaces "not cartoonish".
 *
 * Every clause here is load-bearing. Without the linework clause the model
 * paints glossy cartoon eyes that belong to a different app; without the
 * "never a character" clause it grows arms and legs; without "no pupils, no
 * highlights" it drifts toward a plush toy. Five marks, in the grey already on
 * the page.
 */
const FACE_RULE = `- It has a face, and the face is made ONLY of the same sparse, fine, warm grey linework as the rest of the drawing: two small round eyes, two short brows tilted up at their inner ends, and one simple downturned mouth. Nothing else.
- The face is drawn flat onto the subject, small and quiet, sitting in the middle of its body. No pupils, no eyelashes, no highlights, no glossy shine, no blush, no cheeks, no tongue, no teeth, and absolutely no arms, legs, hands, feet or limbs of any kind.
- It is an ingredient with a face drawn on it — never a character, a mascot, a creature, a toy or a cartoon animal, and it is never standing up or doing anything.`;

/**
 * Takes the "not cartoonish" clause out of the shared trailer.
 *
 * Throws rather than degrading: a silent miss would emit the unmodified style,
 * the model would obey it, and five renders would come back faceless with
 * nothing saying why.
 */
const CARTOON_CLAUSE = " not cartoonish,";

const allowDrawnFace = (style: string) => {
    if (!style.includes(CARTOON_CLAUSE)) {
        throw new Error(
            `The shared trailer no longer contains "${CARTOON_CLAUSE.trim()}". ` +
                `generate-crash-art removes that clause on purpose and cannot ` +
                `silently stop doing so — re-read buildFoodIllustrationStyle's ` +
                `trailer and update CARTOON_CLAUSE.`
        );
    }

    return style.replace(CARTOON_CLAUSE, "");
};

const STYLE = allowDrawnFace(
    buildFoodIllustrationStyle({
        vessel: "none",
        // Three-quarter, not the medallions' overhead: a face seen from
        // directly above is a face you cannot see.
        camera: "three-quarter",
        framing:
            "the ingredient is centred in a square frame and fills about two thirds of its width and height, leaving a generous, completely even margin of empty ground on all four sides. Nothing touches or is cropped by an edge, and nothing at all sits in the corners of the frame.",
        renderingEmphasis:
            "The drawn face is the smallest and quietest thing in the picture — a few fine grey marks, never inked heavier or darker than the linework around it.",
        mood: "sorry for itself, and completely fine — nothing here is ruined.",
    })
);

/** One subject per candidate. The face is constant; the way it sags is not. */
const SUBJECTS: Record<string, string> = {
    /** Round, pale, and the shoot gives the droop somewhere to happen. */
    onion: `Editorial illustration of one small onion that has wilted, with a sad face drawn on it.

SUBJECT
- ONE small round onion, and nothing else in the picture. Its papery skin is pale with a soft warm blush and fine vertical lines.
- Its single green shoot has flopped right over sideways and hangs limply down past its shoulder; a second, shorter shoot droops the other way. A few fine roots trail from the base.
- The whole bulb sits a little squat, as though it has slumped.`,

    /** The split is the failure, and the strongest colour of the five. */
    tomato: `Editorial illustration of one tomato that has split, with a sad face drawn on it.

SUBJECT
- ONE ripe round tomato, and nothing else in the picture.
- Its skin has split open in one clean curving crack down its side, and it has slumped a little out of round where it gave — it sits lower on one side than the other.
- Its small green calyx on top has wilted and curled downward.
- The tomato is fresh and whole apart from that one split: nothing is mouldy, spotted, shrivelled, rotten or dirty.`,

    /** The best silhouette of the five, and the one that bends most naturally. */
    aubergine: `Editorial illustration of one aubergine that has gone limp, with a sad face drawn on it.

SUBJECT
- ONE whole deep-purple aubergine, and nothing else in the picture. It is lying down rather than standing.
- It has gone soft and bent: its body sags into a gentle downward curve in the middle, and its narrow end droops toward the ground.
- Its green calyx and stalk at the top have wilted and tipped over.
- The skin is smooth and whole: nothing is mouldy, spotted, shrivelled, rotten or dirty.`,

    /** Long and thin, so the bend reads even at thumbnail size. */
    carrot: `Editorial illustration of one carrot that has gone limp, with a sad face drawn on it.

SUBJECT
- ONE whole orange carrot, and nothing else in the picture. It is lying down rather than standing.
- It has lost its stiffness: the body bends in a soft downward arc and its tip curls over, the way a carrot does after a week in a drawer.
- The feathery green tops at its thick end have wilted and flopped over to one side.
- The carrot is smooth and whole: nothing is mouldy, spotted, shrivelled, rotten or dirty.`,

    /** The only one whose failure is a break rather than a droop. */
    egg: `Editorial illustration of one egg with a cracked shell, with a sad face drawn on it.

SUBJECT
- ONE whole pale egg, lying on its side, and nothing else in the picture but its own shell.
- A single jagged crack runs across its upper shell, and one small piece of shell has come away and rests beside it, so the break is obvious.
- The egg is not broken open and nothing has spilled out of it: the yolk and white are still inside and unseen.`,
};

const MODEL = (process.env.GENAI_IMAGE_MODEL ??
    "gemini-3.1-flash-image") as Parameters<typeof generateImage>[0]["model"];

const OUT_DIR = join(process.cwd(), "operations", "output", "crash-art");

/** This endpoint returns JPEG; see `generate-splash`. */
const extensionFor = (mimeType: string) =>
    mimeType.includes("jpeg") || mimeType.includes("jpg") ? "jpg" : "png";

const only = process.argv.find((a) => a.startsWith("--only="))?.split("=")[1];

async function main() {
    mkdirSync(OUT_DIR, { recursive: true });

    const entries = Object.entries(SUBJECTS).filter(
        ([name]) => !only || name === only
    );

    console.log("=== Crash screen candidates ===\n");
    console.log(`Model: ${MODEL}`);
    console.log(`${entries.length} subjects\n`);

    let failed = 0;

    for (const [name, subject] of entries) {
        try {
            console.log(`Generating ${name}...`);

            const { base64Data, mimeType } = await generateImage({
                prompt: `${subject}
${FACE_RULE}
${SINGLE_IMAGE_RULE}

${STYLE}`,
                model: MODEL,
                aspectRatio: "1:1",
            });

            if (!base64Data) {
                throw new Error(
                    `Model returned no image data for ${name} — the prompt likely produced a text response.`
                );
            }

            const file = `${name}.${extensionFor(mimeType)}`;
            writeFileSync(
                join(OUT_DIR, file),
                Buffer.from(base64Data, "base64")
            );
            console.log(`✓ ${file}`);
        } catch (error) {
            failed++;
            console.error(
                `✗ ${name}: ${error instanceof Error ? error.message : error}`
            );
        }
        // Same spacing as the other image operations.
        await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    console.log(`\nWritten to ${OUT_DIR}`);
    // The winner is downscaled to 640px on the way in — see `ArtMedallion`,
    // which documents why the raw 1024 render is not what gets committed.
    console.log(
        "\nInstall the one you pick:\n" +
            "  sips -Z 640 --setProperty format jpeg --setProperty formatOptions 70 \\\n" +
            "    operations/output/crash-art/<name>.jpg \\\n" +
            "    --out ../../../Projects/fridgeezy/src/assets/images/illustrations/souffle.jpg\n" +
            "\nThe client seam is `ArtMedallion`'s ART map + ErrorState's `crash` kind."
    );
    if (failed > 0) process.exitCode = 1;
}

main();
