#!/usr/bin/env bash
#
# Push the sign-in email templates to the hosted project.
#
# **Do not use `supabase config push` for this.** That command sends the whole
# `[auth]` block, and this repo's `config.toml` is the LOCAL stack's config —
# `site_url` is 127.0.0.1:3000, `[auth.email.smtp]` is a Resend key that only
# delivers to one address, and `[auth.external.apple]` is `enabled = false`
# while production ships Apple Sign-In. Pushing it would point prod's redirects
# at localhost and turn Apple off. This script PATCHes named fields and touches
# nothing else.
#
# TWO templates are written, not one, and that is the fix for "production still
# sends the autogenerated mail". The app's only way in is
# `signInWithOtp({ shouldCreateUser: true })`, and GoTrue picks the template by
# whether the address is already known: an existing user gets `magic_link`, a
# brand new one gets `confirmation` for as long as the project has email
# confirmations on. Pushing magic_link alone therefore fixes returning users and
# leaves every FIRST-TIME signup on Supabase's default link mail — which is the
# half most likely to be noticed, and the half that cannot be completed at all,
# since the app has no deep link for a confirmation URL and only ever calls
# `verifyOtp`. Both templates carry `{{ .Token }}`, and the app verifies with
# `type: "email"`, which GoTrue accepts for either.
#
# `--check` prints every template the hosted project holds, so a mail that is
# still coming through as a default can be attributed to the right one.
#
# Needs a Supabase personal access token — from SUPABASE_ACCESS_TOKEN, or the
# one `supabase login` left in the macOS keychain.
#
#   ./operations/push-magic-link-template.sh            # show remote, then ask
#   ./operations/push-magic-link-template.sh --check    # show remote only
set -euo pipefail

PROJECT_REF="${PROJECT_REF:-qkxznjwlybjqpcauaisz}"
TEMPLATE="$(dirname "$0")/../supabase/templates/magic-link.html"
SUBJECT="Your Fridgeezy sign-in code"
API="https://api.supabase.com/v1/projects/${PROJECT_REF}/config/auth"

TOKEN="${SUPABASE_ACCESS_TOKEN:-}"
if [ -z "$TOKEN" ]; then
  # `supabase login` writes this item under the account "supabase"; older CLI
  # versions used "access-token". Try both, or a token that is present under the
  # other name is reported as no token at all.
  for ACCOUNT in supabase access-token; do
    TOKEN="$(security find-generic-password -s 'Supabase CLI' -a "$ACCOUNT" -w 2>/dev/null || true)"
    [ -n "$TOKEN" ] && break
  done
fi
if [ -z "$TOKEN" ]; then
  echo "No token. Export SUPABASE_ACCESS_TOKEN (https://supabase.com/dashboard/account/tokens)." >&2
  exit 1
fi

echo "== remote auth mail, before =="
curl -sf -H "Authorization: Bearer $TOKEN" "$API" | python3 -c '
import sys, json

config = json.load(sys.stdin)

# mailer_autoconfirm true means "no confirmation mail is sent at all", so a new
# address goes straight down the magic_link path and `confirmation` is dead.
print("email confirmations:", "off" if config.get("mailer_autoconfirm") else "ON — a NEW address gets `confirmation`, not `magic_link`")
print("otp length:", config.get("mailer_otp_length"))
print()

for key, label in [
    ("magic_link", "magic_link   (returning user)"),
    ("confirmation", "confirmation (first-time signup)"),
    ("recovery", "recovery"),
    ("email_change", "email_change"),
    ("invite", "invite"),
]:
    body = config.get(f"mailer_templates_{key}_content") or ""
    subject = config.get(f"mailer_subjects_{key}") or "(default)"
    if not body:
        state = "hosted default"
    elif ".Token" in body:
        state = "custom, carries the code"
    else:
        state = "custom, NO .Token <- the code can never arrive"
    print(f"  {label:34} {state}")
    print(f"  {"":34} subject: {subject}")
'

if [ "${1:-}" = "--check" ]; then exit 0; fi

read -r -p "Overwrite the hosted magic_link AND confirmation templates? [y/N] " reply
[ "$reply" = "y" ] || { echo "aborted"; exit 0; }

python3 -c '
import json, sys

subject, path = sys.argv[1], sys.argv[2]
body = open(path).read()
payload = {}
for key in ("magic_link", "confirmation"):
    payload[f"mailer_subjects_{key}"] = subject
    payload[f"mailer_templates_{key}_content"] = body
print(json.dumps(payload))
' "$SUBJECT" "$TEMPLATE" \
| curl -sf -X PATCH "$API" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    --data-binary @- \
| python3 -c '
import sys, json

config = json.load(sys.stdin)
print("pushed.")
for key in ("magic_link", "confirmation"):
    body = config.get(f"mailer_templates_{key}_content") or ""
    print(f"  {key:13} subject: {config.get(f"mailer_subjects_{key}")!r}  carries the code: {"yes" if ".Token" in body else "NO"}")
'
